POST http://lb-b6fe3fce.elb.localhost.localstack.cloud:4000/patients
Content-Type: application/json

{
  "name": "kafka_test",
  "email": "kafka_test@example.com",
  "address": "123 main",
  "dateOfBirth": "2002-10-07",
  "registeredDate": "2020-10-31"
}